name: Azure Docker Deployment

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-build-push-container-azure.yml@55-azure-workflow-deployment-missing
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit

  deploy:
    needs: build
    uses: ai-cfia/github-workflows/.github/workflows/workflow-deploy-azure.yml@55-azure-workflow-deployment-missing
    with:
      container-name: ${{ github.event.repository.name }}
      tag: ${{ github.sha }}
    secrets: inherit
